In [93]:
# @title: Exercicio 03 Pandas

import pandas as pd
import numpy as np

1 - Crie um DataFrame com as colunas nome, idade, altura, peso e sexo usando listas.

In [113]:
# criando numpy array por motivo de dados homogêneos
names = np.array(['João', 'Maria', 'José', 'Ana', 'Pedro'])
ages = np.array([25, 30, 35, 40, 45])
heights = np.array([1.75, 1.65, 1.80, 1.60, 1.70])
weights = np.array([75, 65, 80, 98, 70])
genders = np.array(['M', 'F', 'M', 'F', 'M'])

# criando um dataframe pandas atraves de lista
data = {
    'name': names,
    'age': ages,
    'height': heights,
    'weight': weights,
    'gender': genders
}
df = pd.DataFrame(data)

Exiba o DataFrame criado.

In [95]:
df

name  age  height  weight gender
0   João   25    1.75      75      M
1  Maria   30    1.65      65      F
2   José   35    1.80      80      M
3    Ana   40    1.60      98      F
4  Pedro   45    1.70      70      M

3 - Selecione e exiba a coluna "idade" do DataFrame.

In [116]:
df['age']

0    25
1    30
2    35
3    40
4    45
Name: age, dtype: int64

4 - Selecione e exiba a linha com índice 2 do DataFrame.

In [117]:
df.iloc[[2]]

name  age  height  weight gender
2  José   35     1.8      80      M

5 - Selecione e exiba a linha com rótulo 2 do DataFrame.[link text](https://)


In [118]:
df.loc[[2]]

name  age  height  weight gender
2  José   35     1.8      80      M

6 - Selecione e exiba o valor da célula na linha de rótulo 3, coluna "altura".

---



In [119]:
a = df.loc[3,'name']
print(a)

Ana


7 - Renomeie as colunas "sexo" para "genero" e "peso" para "massa".

In [120]:
df.rename(columns={'gender': 'genre', 'weight': 'mass'}, inplace=True)
df


name  age  height  mass genre
0   João   25    1.75    75     M
1  Maria   30    1.65    65     F
2   José   35    1.80    80     M
3    Ana   40    1.60    98     F
4  Pedro   45    1.70    70     M

8 - Selecione e exiba as colunas "nome" e "altura" do DataFrame.

In [122]:
df[['name', 'height']]

name  height
0   João    1.75
1  Maria    1.65
2   José    1.80
3    Ana    1.60
4  Pedro    1.70

9 - Filtre e exiba todas as linhas onde a idade é maior que 40.

In [123]:
df[df['age'] > 40]

name  age  height  mass genre
4  Pedro   45     1.7    70     M

10 - Adicione uma nova coluna chamada "IMC" ao DataFrame, calculando o Índice de Massa Corporal.

In [127]:
df['IMC'] = (df['mass'] / (df['height'] ** 2)).round(decimals=2)
df



name  age  height  mass genre    IMC
0   João   25    1.75    75     M  24.49
1  Maria   30    1.65    65     F  23.88
2   José   35    1.80    80     M  24.69
3    Ana   40    1.60    98     F  38.28
4  Pedro   45    1.70    70     M  24.22

11 - Ordene o DataFrame pela coluna "altura" em ordem crescente.

In [128]:
df.sort_values(by='height')

name  age  height  mass genre    IMC
3    Ana   40    1.60    98     F  38.28
1  Maria   30    1.65    65     F  23.88
4  Pedro   45    1.70    70     M  24.22
0   João   25    1.75    75     M  24.49
2   José   35    1.80    80     M  24.69

12 - Filtre e exiba todas as linhas onde a altura é  maior que 1.65.

In [129]:
df[df['height'] > 1.65]

name  age  height  mass genre    IMC
0   João   25    1.75    75     M  24.49
2   José   35    1.80    80     M  24.69
4  Pedro   45    1.70    70     M  24.22

13 - Modifique a altura de alguém para 1.91 e exiba o DataFrame.

In [130]:
df.loc[2, 'height'] = 1.91
df

name  age  height  mass genre    IMC
0   João   25    1.75    75     M  24.49
1  Maria   30    1.65    65     F  23.88
2   José   35    1.91    80     M  24.69
3    Ana   40    1.60    98     F  38.28
4  Pedro   45    1.70    70     M  24.22

14 - Crie uma coluna com valores de CPF para cada linha

In [143]:
import random
random.seed(42)
aleaotory = lambda:random.randint(11111111111,99999999999)
df['CPF'] = [aleaotory() for _ in range(len(df['name'])) ]


#forma melhor encontrado na internet
df['CPF'] = np.random.randint(11111111111, 99999999999, size=len(df))
df

name  age  height  mass genre    IMC          CPF
0   João   25    1.75    75     M  24.49  40750042562
1  Maria   30    1.65    65     F  23.88  66677512873
2   José   35    1.91    80     M  24.69  56791372830
3    Ana   40    1.60    98     F  38.28  42986934964
4  Pedro   45    1.70    70     M  24.22  87893221779

15. Exclua a coluna CPF do DataFrame.

In [144]:
del df['CPF']
df

name  age  height  mass genre    IMC
0   João   25    1.75    75     M  24.49
1  Maria   30    1.65    65     F  23.88
2   José   35    1.91    80     M  24.69
3    Ana   40    1.60    98     F  38.28
4  Pedro   45    1.70    70     M  24.22

 Resete o índice do DataFrame e exiba o resultado.


In [145]:
df.reset_index(drop=True, inplace=True)
df

name  age  height  mass genre    IMC
0   João   25    1.75    75     M  24.49
1  Maria   30    1.65    65     F  23.88
2   José   35    1.91    80     M  24.69
3    Ana   40    1.60    98     F  38.28
4  Pedro   45    1.70    70     M  24.22

17 - Exiba as linhas do DataFrame onde a altura é maior que 1.70.

In [146]:
df[df['height'] > 1.70]

name  age  height  mass genre    IMC
0  João   25    1.75    75     M  24.49
2  José   35    1.91    80     M  24.69

18 - Selecione e exiba as colunas "nome" e "genero".

In [147]:
df[['name', 'genre']]

name genre
0   João     M
1  Maria     F
2   José     M
3    Ana     F
4  Pedro     M

19 - Calcule e exiba a soma das idades.

In [148]:
df['age'].sum()

175

20 - Salve o DataFrame em um arquivo CSV.

In [149]:
df.to_csv('dados.csv', index=False)